version: '3.7'
services:
  users_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  users_app:
    image: siarheisvila/users-application:1.0.0
    environment:
      - DB_URL=jdbc:postgresql://users_db:5432/users
      - DB_USERNAME=admin
      - DB_PASSWORD=admin1234
    ports:
      - "8081:8080"
    depends_on:
      - users_db
volumes:
  pgdata: