apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: users-app
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: users-app-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: users-app-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: users-app-pod
        owner: siarheisvila
    spec:
      containers:
        - name: users-container
          image: siarheisvila/users-application:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:postgresql://users-db/users
            - name: DB_USERNAME
              value: admin
            - name: DB_PASSWORD
              value: admin1234